# setup-hook.ps1 — 安装 post-commit git hook（Windows）
# 用法: powershell -ExecutionPolicy Bypass -File setup-hook.ps1 [[-ProjectRoot] <path>]

param(
    [string]$ProjectRoot = ""
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ── 确定项目根目录 ──────────────────────────────
if (-not $ProjectRoot) {
    $ProjectRoot = Resolve-Path "$ScriptDir\..\..\.."
}

Set-Location $ProjectRoot
$GitDir = git rev-parse --git-dir 2>$null
if (-not $GitDir) {
    Write-Host "[git-commit-clone] ERROR: ${ProjectRoot} is not a git repository"
    exit 1
}

$HookFile = Join-Path $GitDir "hooks\post-commit"
$SnapshotScript = Join-Path $ScriptDir "clone-snapshot.ps1"

# ── 检查依赖 ────────────────────────────────────
if (-not (Test-Path $SnapshotScript)) {
    Write-Host "[git-commit-clone] ERROR: clone-snapshot.ps1 not found at ${SnapshotScript}"
    exit 1
}

# ── 确保 hooks 目录存在 ────────────────────────
$HooksDir = Join-Path $GitDir "hooks"
if (-not (Test-Path $HooksDir)) { New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null }

# ── 写入 hook ───────────────────────────────────
$HookContent = @"
#!/bin/sh
# post-commit hook — auto-generated by git-commit-clone skill
# 每次 git commit 后自动创建项目浅克隆快照

SNAPSHOT_SCRIPT="${SnapshotScript}"
if [ -f "\$SNAPSHOT_SCRIPT" ]; then
    PROJECT_ROOT=\$(git rev-parse --show-toplevel 2>/dev/null)
    REP_DIR="\${PROJECT_ROOT}/.claude/repo/project"
    mkdir -p "\$REP_DIR"
    cd "\$PROJECT_ROOT" && powershell -ExecutionPolicy Bypass -File "\$SNAPSHOT_SCRIPT" &>/dev/null &
    disown
fi
"@

$HookContent | Set-Content -Path $HookFile -Encoding ASCII

# ── 验证 ────────────────────────────────────────
Write-Host "[git-commit-clone] post-commit hook installed at: ${HookFile}"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Run: git commit (to test auto-snapshot)"
Write-Host "  2. Check: ls .claude/repo/project/"
