#!/bin/bash
# setup-hook.sh — 安装 post-commit git hook，自动触发快照
# 用法: bash setup-hook.sh
# 从 skills/git-commit-clone/reference/ 目录执行，或传入项目根路径

set -euo pipefail

# ── 确定项目根目录 ──────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ $# -ge 1 ]; then
    PROJECT_ROOT="$1"
else
    PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
fi

# 检查是否是 git 仓库
if ! cd "$PROJECT_ROOT" && git rev-parse --git-dir >/dev/null 2>&1; then
    echo "[git-commit-clone] ERROR: ${PROJECT_ROOT} is not a git repository"
    exit 1
fi

GIT_DIR="${PROJECT_ROOT}/.git"
HOOK_FILE="${GIT_DIR}/hooks/post-commit"
SNAPSHOT_SCRIPT="${SCRIPT_DIR}/clone-snapshot.sh"

# ── 检查依赖 ────────────────────────────────────
if [ ! -f "$SNAPSHOT_SCRIPT" ]; then
    echo "[git-commit-clone] ERROR: clone-snapshot.sh not found at ${SNAPSHOT_SCRIPT}"
    exit 1
fi

# ── 创建 hooks 目录（可能不存在） ──────────────
mkdir -p "${GIT_DIR}/hooks"

# ── 写入 hook ───────────────────────────────────
cat > "$HOOK_FILE" << 'HOOK_HEADER'
#!/bin/bash
# post-commit hook — auto-generated by git-commit-clone skill
# 每次 git commit 后自动创建项目浅克隆快照

set -euo pipefail
HOOK_HEADER

# shellcheck disable=SC2129
echo "" >> "$HOOK_FILE"
echo "# ── git-commit-clone snapshot ──" >> "$HOOK_FILE"
echo "SNAPSHOT_SCRIPT=\"${SNAPSHOT_SCRIPT}\"" >> "$HOOK_FILE"
echo 'if [ -f "$SNAPSHOT_SCRIPT" ]; then' >> "$HOOK_FILE"
echo '    PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)' >> "$HOOK_FILE"
echo '    REP_DIR="${PROJECT_ROOT}/.claude/repo/project"' >> "$HOOK_FILE"
echo '    mkdir -p "$REP_DIR"' >> "$HOOK_FILE"
echo '    cd "$PROJECT_ROOT" && bash "$SNAPSHOT_SCRIPT" &>/dev/null &  # 后台执行，不阻塞 commit' >> "$HOOK_FILE"
echo '    disown' >> "$HOOK_FILE"
echo 'fi' >> "$HOOK_FILE"

chmod +x "$HOOK_FILE"

echo "[git-commit-clone] ✓ post-commit hook installed at: ${HOOK_FILE}"
echo "[git-commit-clone] ✓ snapshot script: ${SNAPSHOT_SCRIPT}"
echo ""
echo "Next steps:"
echo "  1. Verify: ls -la \"${HOOK_FILE}\""
echo "  2. Run a commit to test auto-snapshot"
echo "  3. Check: ls -la \"${PROJECT_ROOT}/.claude/repo/project/\""
